import type { Metadata } from "next";
import { Header } from "~/components/header";
import { fonts } from "~/config/fonts";
import "~/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className={fonts.sans.variable}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
